### ISSUE TITLE
Add new section for Web Performance courses?

### ISSUE THREAD

**Issue by AndrewCraswell** [davidsonfellipe/awesome-wpo#103]
For my organization, I maintain a list of web performance courses that I've found useful. I noticed that there was another closed issue regarding adding a course as a "talk", but to me, these are different things. Is there any opposition to adding a new section for courses and keeping these separate from talks?

Here are a few that I am aware of:
[[Pluralsight] Website Performance](https://app.pluralsight.com/library/courses/website-performance/table-of-contents)
[[Pluralsight] Web Performance](https://app.pluralsight.com/library/courses/web-performance/table-of-contents)
[[Pluralsight] Using Google PageSpeed Insights to Improve Web Performance](https://app.pluralsight.com/library/courses/google-pagespeed-insights-web-performance/table-of-contents)
[[Pluralsight] A Web Developers Guide To Images](https://app.pluralsight.com/library/courses/dev-guide-to-images/table-of-contents)
[[Pluralsight] Responsive Web Images](https://app.pluralsight.com/library/courses/responsive-web-images/table-of-contents)
[[Pluralsight] Tracking Real World Web Performance](https://app.pluralsight.com/library/courses/web-performance-tracking/table-of-contents)
[[LinkedIn Learning] Designing Websites for Performance](https://www.linkedin.com/learning/designing-websites-for-performance)
[[LinkedIn Learning] Automated Web Performance Load Testing](https://www.linkedin.com/learning/devops-with-visual-studio-team-services/automated-web-performance-load-testing)
[[LinkedIn Learning] HTTP/2: Developing for Performance](https://www.linkedin.com/learning/http-2-developing-for-performance)
[[Channel9] Web Performance](https://channel9.msdn.com//Shows/Web-Hack-Wednesday/Web-Performance/)

Hope this helps contribute to this awesome resource!

**Comment by davidsonfellipe** [comment]
@AndrewCraswell good one, can you send a PR following this format [1], in a separated file COURSES.md?

https://github.com/davidsonfellipe/awesome-wpo/blob/master/BLOGS.md
