### ISSUE TITLE
Talks Video (turbocharging wordpress)

### ISSUE THREAD

**Issue by grandmst** [davidsonfellipe/awesome-wpo#43]
Not sure if this is worth adding, due to it coming from a technical SEO perspective, as it includes wordpress specific stuff, and a few tips that can be used on a general basis. 

https://www.jonoalderson.com/events-presentations/searchlove-2014-turbo-charging-wordpress-website-cheat-sheet/

But though i would submit for review anyway.

**Comment by davidsonfellipe** [comment]
@grandmst please create a new category "wordpress" on https://github.com/davidsonfellipe/awesome-wpo/blob/master/TALKS.md, and link + language.
