### ISSUE TITLE
DevTools Course

### ISSUE THREAD

**Issue by felfiz** [davidsonfellipe/awesome-wpo#44]
CodeSchool has a course about Chrome DevTools that talks a lot about performance, not only about loading performance but about memory, cpu, animation performance, etc.

Can i add ?

**Comment by davidsonfellipe** [comment]
@felfiz Yes, you can. Please add in https://github.com/davidsonfellipe/awesome-wpo/blob/master/TALKS.md

**Comment by davidsonfellipe** [comment]
@felfiz thanks
