### ISSUE TITLE
grunt compress, innosetup

### ISSUE THREAD

**Issue by emalherbi** [davidsonfellipe/awesome-wpo#51]
Hey there!

What do you think of the possibility of adding [grunt-contrib-compress](https://github.com/gruntjs/grunt-contrib-compress) for generate zip or tar compress. And also add the [innosetup-compiler](https://github.com/felicienfrancois/node-innosetup-compiler). ?

When I need to send my client the updated sources of the project, I send him a .rar or .exe for updating. For many customers have not ability to perform updating servers, etc.

Thank you.

**Comment by marcobiedermann** [comment]
:-1: @emalherbi I think adding a tool, which can zip your project does not affect your websites performance. Yeah, you are right, it is great for sending some packages, but it does not optimize any resources on your site.

**Comment by emalherbi** [comment]
I understand and I think you have reason.

**Comment by davidsonfellipe** [comment]
@marcobiedermann @emalherbi thank you guys

**Comment by davidsonfellipe** [comment]
@emalherbi thanks by attempt, if you have more suggestions feel free to do.
