### ISSUE TITLE
New Additions to WPO Listings 

### ISSUE THREAD

**Issue by AmyVosters** [davidsonfellipe/awesome-wpo#55]
Under the *Analyzers* and *Metrics Monitor* sections would be great to add:

**Analyzers**
[CloudTest] (http://www.soasta.com/products/cloudtest/) - Simulates realistic traffic for load and performance testing for web and mobile applications at any scale from the cloud. Real-time analytics dashboards allow for an integrative view of live data while tests run, with the ability to test at any scale. 

**Metrics Monitor**
[mPulse] (http://www.soasta.com/products/mpulse/) - Real-User Monitoring tool from SOASTA that allows for the measurement all real-user behavior on mobile and web apps in real-time.

**Comment by davidsonfellipe** [comment]
@AmyVosters please create a pull request with this ones.
