### ISSUE TITLE
Social media buttons

### ISSUE THREAD

**Issue by fourtonfish** [davidsonfellipe/awesome-wpo#57]
I both wrote [an article](http://blog.fourtonfish.com/post/60892231273/simple-sharing-buttons-free) and made a [little tool](http://simplesharingbuttons.com) that helps create sharing buttons for many popular social media sites that don't rely on loading a ton of third party JavaScript -- in case this sounds interesting to you.

**Comment by davidsonfellipe** [comment]
@fourtonfish thanks, but isn't related to this list.
