### ISSUE TITLE
PageSpeed

### ISSUE THREAD

**Issue by kiquenet** [davidsonfellipe/awesome-wpo#74]
Note: 
**PageSpeed Insights for Google Chrome has been deprecated. Please use the online version of PageSpeed Insights.**

***Workaround***

For Google Page Speed extension:

Maybe any partner in your company has installed the extension. Then do this::

Open _chrome://version/_ and look for **Profile Path**:
 
_C:\Users\<Your_User_Name>\AppData\Local\Google\Chrome\User Data\Default\Extensions_ 

Then, copy subfolder ***gplegfbjlmmehdoakndmohflojccocli***, without  _metadata folder.

For use it, open _chrome://extensions/_ and activate Developer Mode. And Load unzipped extension.

**Comment by davidsonfellipe** [comment]
@kiquenet updated, thanks!

**Comment by davidsonfellipe** [comment]
@kiquenet 
<img width="820" alt="yas" src="https://cloud.githubusercontent.com/assets/381179/8802121/4337260c-2f8d-11e5-98ff-fc645d6a784b.png">

**Comment by kiquenet** [comment]
Only a comment.

Page Speed Insights, now only online version is available, not Chrome Extension (deprecated)
https://developers.google.com/speed/pagespeed/insights/
