### ISSUE TITLE
suggestion: Glimpse

### ISSUE THREAD

**Issue by kiquenet** [davidsonfellipe/awesome-wpo#76]
***http://getglimpse.com/***

**Once installed, Glimpse inspects web requests as they happen, providing insights and tooling that reduce debugging time and empower every developer to improve their web applications.**

_Nik Molnar and Anthony van der Hoorn, the creators of Glimpse, have joined Microsoft on the Visual Studio team!
http://blogs.msdn.com/b/webdev/archive/2015/07/14/a-glimpse-into-the-future-of-web-development-tools.aspx_

**Comment by davidsonfellipe** [comment]
@kiquenet Please, can you create a Pull Request adding this?
