### ISSUE TITLE
New content for inclusion

### ISSUE THREAD

**Issue by symcbean** [davidsonfellipe/awesome-wpo#94]
I would be very grateful if you would consider my blog and book for inclusion in the project:

http://lampe2e.blogspot.co.uk/

https://play.google.com/store/books/details/Colin_McKinnon_Linux_Apache_MySQL_PHP_Performance?id=Z3ciBgAAQBAJ

C.

**Comment by davidsonfellipe** [comment]
@symcbean done, thanks!
