### ISSUE TITLE
Add new Optimization Link

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [davidsonfellipe/awesome-wpo#95]
https://observatory.mozilla.org/

**Comment by denji** [comment]
https://varvy.com/

**Comment by davidsonfellipe** [comment]
@denji Varvy added.

**Comment by davidsonfellipe** [comment]
@IgnaciodeNuevo Observatory is more related to Security, right?

**Comment by IgnaciodeNuevo** [comment]
Sorry, right its security related

**Comment by davidsonfellipe** [comment]
@IgnaciodeNuevo no problem, thanks!
